default: &default
  adapter: postgresql
  encoding: unicode
  database: new_discuss_app
  username: postgres
  password: postgres
  host: localhost
  port: 5432

development:
  <<: *default

test:
  <<: *default
production:
  <<: *default